"""empty message

Revision ID: 8277973f3bd6
Revises: bc11d2b7e830
Create Date: 2022-10-18 03:30:05.096509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8277973f3bd6'
down_revision = 'bc11d2b7e830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite_planet', sa.Column('name', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'favorite_planet', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorite_planet', type_='unique')
    op.drop_column('favorite_planet', 'name')
    # ### end Alembic commands ###
